[package]
name = "cliutil"
description = "A command line utilities library"
authors = [ "Jacob Green" ]
version = "0.0.2"
license = "Apache-2.0"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/jacobrgreen114/cliutil-rs"
edition = "2021"
